version: '3.5'

services:
    backend:
        container_name: amojuliana
        build:
            context: .
            dockerfile: Dockerfile
        image: amojuliana
        environment:
            DB_CONNECTION: mysql
            DB_HOST: ${vars.DB_HOST}
            DB_PORT: 3306
            DB_USERNAME: ${vars.DB_USERNAME}
            DB_PASSWORD: ${vars.DB_PASSWORD}
            DB_DATABASE: ${vars.DB_DATABASE}
        ports:
            - "80:80"
        volumes:
            - .:/app
