version: '3.5'

services:
    backend:
        container_name: amojuliana
        build:
            context: .
            dockerfile: Dockerfile
        image: amojuliana
        ports:
            - "80:80"
        volumes:
            - .:/app
