version: '3.5'

services:
    backend:
        container_name: amojuliana
        build:
            context: .
            dockerfile: Dockerfile
        image: amojuliana
        env_file: .env
        ports:
            - "8080:8080"
        volumes:
            - .:/app
